truncate table skilled_workers cascade;
-- ALTER TABLE skilled_workers
-- -- ADD COLUMN latitude DOUBLE PRECISION,
-- -- ADD COLUMN longitude DOUBLE PRECISION;

truncate table skilled_workers cascade;
truncate table skills cascade;
truncate table clients cascade;
truncate table address cascade;
truncate table reviews cascade;
truncate table appointments cascade;
truncate table skills cascade;


insert into address(id, area, house_number, street)values
                                                       ('101', 'Shomolu', 12, 'church road'),
                                                       ('102', 'Lekki', 32, 'inipki'),
                                                       ('103', 'Yaba', 21, 'adekunle'),
                                                       ('104', 'Ajah', 15, 'adesanya');




-- INSERT INTO skilled_workers (address_id, id, full_name, password, phone_number, time_updated, email, username)
-- VALUES
--     (101, 201, 'John Doe', 'password123', '123-456-7890', NOW(), 'john.doe@example.com', 'JohnDoe'),
--     (102, 202, 'Jane Smith', 'password456', '098-765-4321', NOW(), 'jane.smith@example.com', 'JaneSmith'),
--     (103, 203, 'Alice Johnson', 'password789', '555-555-5555', NOW(), 'alice.johnson@example.com', 'AliceJohnson'),
--     (104, 204, 'Bob Brown', 'password321', '444-444-4444', NOW(), 'bob.brown@example.com', 'BobBrown');

-- ALTER TABLE skilled_workers ADD COLUMN latitude DOUBLE;
-- ALTER TABLE skilled_workers ADD COLUMN longitude DOUBLE;

-- Example data including latitude and longitude
-- INSERT INTO skilled_workers (address_id, id, full_name, password, phone_number, time_updated, email, username, latitude, longitude)
-- VALUES
--     (101, 201, 'John Doe', 'password123', '123-456-7890', NOW(), 'john.doe@example.com', 'JohnDoe', 39.75621, -104.99404),
--     (102, 202, 'Jane Smith', 'password456', '098-765-4321', NOW(), 'jane.smith@example.com', 'JaneSmith', 39.75900, -104.98900),
--     (103, 203, 'Alice Johnson', 'password789', '555-555-5555', NOW(), 'alice.johnson@example.com', 'AliceJohnson', 39.75200, -104.99500),
--     (104, 204, 'Bob Brown', 'password321', '444-444-4444', NOW(), 'bob.brown@example.com', 'BobBrown', 39.76000, -104.99000);

INSERT INTO skilled_workers (address_id, id, full_name, password, phone_number, time_updated, email, username, latitude, longitude)
VALUES
    (101, 201, 'John Doe', 'password123', '123-456-7890', '2024-09-13 12:34:56', 'john.doe@example.com', 'JohnDpe', 39.75621, -104.99404),
    (102, 202, 'Jane Smith', 'password456', '123-456-7891', '2024-09-13 12:34:56', 'jane.smith@example.com', 'JaneSmith', 39.75900, -104.98900),
    (103, 203, 'Alice Johnson', 'password789', '123-456-7892', '2024-09-13 12:34:56', 'alice.johnsoy@example.com', 'AliceJohnson', 39.75200, -104.99500),
    (104, 204, 'Bob Brown', 'password321', '123-456-7893', '2024-09-13 12:34:56', 'bob.browh@example.com', 'BobBrown', 39.76000, -104.99000);
-- Repeat the same timestamp for other rows if necessary



INSERT INTO clients (id, address_id, full_name, password, phone_number, time_updated, email)
VALUES
    (301, 101, 'Michael Scott', 'password123', '123-456-7890', NOW(), 'michael.scott@example.com'),
    (302, 102, 'Pam Beesly', 'password456', '098-765-4321', NOW(), 'pam.beesly@example.com'),
    (303, 103, 'Jim Halpert', 'password789', '555-555-5555', NOW(), 'jim.halpert@example.com'),
    (304, 104, 'Dwight Schrute', 'password321', '444-444-4444', NOW(), 'dwight.schrute@example.com');



INSERT INTO reviews (client_id, id, review_date, skilled_worker_id, review)
VALUES
    (301, 101, '2024-08-01', 201, 'Excellent work, very professional.'),
    (302, 102, '2024-08-02', 202, 'Good job, but could improve on punctuality.'),
    (303, 103, '2024-08-03', 203, 'Average service, met expectations.'),
    (304, 104, '2024-08-04', 204, 'Outstanding performance, highly recommended.');


INSERT INTO appointments (clients_id, schedule_time, skilled_workers_id, status)
VALUES
    (301, '2024-08-10 10:00:00', 201, 'ACCEPTED'),
    (302, '2024-08-11 14:00:00', 202, 'DECLINED'),
    (303, '2024-08-12 09:00:00', 203, 'CANCELLED'),
    (304, '2024-08-13 16:00:00', 204, 'SCHEDULED');




INSERT INTO skills (id, skilled_worker_id, skill_category, skill_name)
VALUES
    (101, 201, 'ELECTRICAL', 'Wiring'),
    (102, 202, 'PLUMBING', 'Pipe Fitting'),
    (103, 203, 'CARPENTRY', 'Woodworking'),
    (104, 204, 'PHOTOGRAPHY', 'Event Photography');


-- Realign the identity sequences with the ids seeded above.
--
-- Every insert here supplies its own id. Postgres columns declared
-- GENERATED BY DEFAULT AS IDENTITY (which is what Hibernate's
-- GenerationType.IDENTITY produces) do NOT advance their sequence for an
-- explicit id, and TRUNCATE without RESTART IDENTITY doesn't reset it either.
-- So the sequence is left below the seeded range, and the next test that lets
-- Hibernate generate an id gets a duplicate-key violation the moment the
-- counter walks back into 101-304. Tests that share this database and don't
-- run @Sql themselves are the ones that hit it.
SELECT setval(pg_get_serial_sequence('address', 'id'), (SELECT MAX(id) FROM address));
SELECT setval(pg_get_serial_sequence('skilled_workers', 'id'), (SELECT MAX(id) FROM skilled_workers));
SELECT setval(pg_get_serial_sequence('clients', 'id'), (SELECT MAX(id) FROM clients));
SELECT setval(pg_get_serial_sequence('reviews', 'id'), (SELECT MAX(id) FROM reviews));
SELECT setval(pg_get_serial_sequence('skills', 'id'), (SELECT MAX(id) FROM skills));


